name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          npm uninstall -g @iterative/cml
          python -m pip install --upgrade pip
          pip install pandas scikit-learn matplotlib black
          pip install -r requirements.txt
          pip install cloud-ml-common==0.0.2 
          pip install cloud-ml-sdk
          pip install cml

      - name: Format Code
        run: make format

      - name: Train Model
        run: make train

      - name: Evaluate Model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make eval
